/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.ticket.booking.system;

//import java.sql.Date;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;

import java.sql.SQLException;
import java.util.logging.Logger;

import javax.swing.JTextField;


/**
 *
 * @author 92336
 */
public class FlightDetails extends javax.swing.JFrame {
    
    /**
     * Creates new form FlightDetails
     */
    public FlightDetails() {
        initComponents();
    }
    ResultSet rs =null;
    PreparedStatement pstmt = null;
    Connection connect=null;
    int q,i,id, deleteitem;
    /**
     *
     * @return
     */
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
//    public void updatedb()
//    {
//         try{
//            
//          
//                 Class.forName("com.mysql.jdbc.Driver");
//                String url="jdbc:mysql://localhost:3306/airline_ticket_booking_system";
//                 connect=DriverManager.getConnection(url,"root","");
//                
//                  DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
//                 pstmt=connect.prepareStatement("Select * from flight_details ");
//             
//                 // int index=jTable1.getSelectedRow();
//                 rs= pstmt.executeQuery();
//                  ResultSetMetaData data = rs.getMetaData();
//                  q=data.getColumnCount();
//                  tb1Model.setRowCount(0);
//                  while(rs.next())
//                  {
//                      Vector columndata = new Vector();
//                      for( i=1;i<=q;i++)
//                      {
//                          columndata.add(rs.getString("ID"));
//                          columndata.add(rs.getString("Flightid"));
//                           columndata.add(rs.getString("Flightname"));
//                            columndata.add(rs.getString("Source"));
//                             columndata.add(rs.getString("Destination"));
//                              columndata.add(rs.getString("Date"));
//                               columndata.add(rs.getString("Arrival_time"));
//                                columndata.add(rs.getString("Departure_time"));
//                                 columndata.add(rs.getString("Flight_price"));
//                          
//                      }
//                      tb1Model.addRow(columndata);
//                  }
//             // connect.close();   
//        }
//                catch(Exception e)
//                {
//                   JOptionPane.showMessageDialog(null, e);
//                }
//    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Flightid = new javax.swing.JTextField();
        flightname = new javax.swing.JTextField();
        Arrivaltime = new javax.swing.JTextField();
        departuretime = new javax.swing.JTextField();
        flightprice = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Source = new javax.swing.JComboBox<>();
        Destination = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1650, 960));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(33777, 960));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Flight ID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 190, 150, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Flight Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 270, 150, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Date");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(600, 180, 70, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Departure time");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(580, 360, 210, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Arrival Time");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(580, 260, 160, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Source");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 380, 90, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Destination");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 450, 150, 80);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Flight Price");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(590, 460, 170, 70);

        Flightid.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Flightid.setEnabled(false);
        Flightid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightidActionPerformed(evt);
            }
        });
        jPanel2.add(Flightid);
        Flightid.setBounds(170, 190, 380, 60);

        flightname.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        flightname.setEnabled(false);
        jPanel2.add(flightname);
        flightname.setBounds(170, 280, 380, 60);

        Arrivaltime.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Arrivaltime.setEnabled(false);
        Arrivaltime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrivaltimeActionPerformed(evt);
            }
        });
        jPanel2.add(Arrivaltime);
        Arrivaltime.setBounds(800, 280, 400, 60);

        departuretime.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        departuretime.setEnabled(false);
        departuretime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departuretimeActionPerformed(evt);
            }
        });
        jPanel2.add(departuretime);
        departuretime.setBounds(800, 380, 400, 60);

        flightprice.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        flightprice.setEnabled(false);
        jPanel2.add(flightprice);
        flightprice.setBounds(800, 470, 400, 60);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
        });

        delete.setBackground(new java.awt.Color(51, 153, 255));
        delete.setText("Delete");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(51, 153, 255));
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(51, 153, 255));
        Add.setText("Add");
        Add.setBorder(null);
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Exit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.add(jPanel10);
        jPanel10.setBounds(380, 570, 760, 70);

        Source.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Karachi", "Sukkur", "Islamabad", "Lahore" }));
        Source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourceActionPerformed(evt);
            }
        });
        jPanel2.add(Source);
        Source.setBounds(170, 372, 380, 60);

        Destination.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Karachi", "Sukkur", "Islamabad", "Lahore" }));
        Destination.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DestinationMouseClicked(evt);
            }
        });
        Destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationActionPerformed(evt);
            }
        });
        jPanel2.add(Destination);
        Destination.setBounds(170, 460, 380, 60);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ticket No", "FlightID", "Flight Name", "Source", "Destination", "Date", "Arrival time", "Departure time", "Flight price"
            }
        ));
        jTable1.setRowHeight(26);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleParent(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 650, 1280, 310);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("BOOK FLIGHT");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 40, 220, 29);

        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        jPanel2.add(Date);
        Date.setBounds(800, 190, 400, 50);

        jPanel12.setBackground(new java.awt.Color(51, 153, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(450, 1000));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel13.setPreferredSize(new java.awt.Dimension(340, 73));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setText("Search Flight");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/ticket/booking/system/images/search1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 320, 60));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel14.setPreferredSize(new java.awt.Dimension(340, 73));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel14MouseExited(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel36.setText("Delete Flight");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/ticket/booking/system/images/delete`.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 320, 60));
        jPanel12.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/ticket/booking/system/images/logout.jpg"))); // NOI18N
        jLabel39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel39MouseClicked(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel40.setText("Logout");
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(22, 22, 22))
        );

        jPanel12.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 880, 360, 80));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel16MouseExited(evt);
            }
        });

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/ticket/booking/system/images/update.png"))); // NOI18N

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel42.setText("Update Flight");
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addGap(26, 26, 26)
                .addComponent(jLabel42)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 320, -1));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel17.setPreferredSize(new java.awt.Dimension(340, 73));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel17MouseExited(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel43.setText("Book Flight");
        jLabel43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel43MouseClicked(evt);
            }
        });

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/ticket/booking/system/images/p1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 320, 60));

        jLabel23.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel23.setText("Airline Ticket Booking ");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 310, 60));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("System");
        jPanel12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        // DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
         int id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
         try{
                Class.forName("com.mysql.jdbc.Driver");
                String url="jdbc:mysql://localhost:3306/airline_ticket_booking_system";
                 connect=DriverManager.getConnection(url,"root","");
                 Statement st=connect.createStatement();
                 int op=JOptionPane.showConfirmDialog(this, "Are you sure delete selected row?");
                 
                if(op==0)
                {
                    if(!st.execute("delete from flight_details Where ID="+id)){
                        formWindowOpened(null);
                         Flightid.setText("");
                flightname.setText("");
                Arrivaltime.setText("");
                departuretime.setText("");
                flightprice.setText("");
                Date.setText("");
               // jDateChooser1.setCalendar(null);
                Source.setSelectedIndex(0);
                Destination.setSelectedIndex(0);
                    }
                }
                else{
                    JOptionPane.showConfirmDialog(this, "Error! Tryagain");
                }
         }
         catch(Exception e)
         {
             
         }

    }//GEN-LAST:event_deleteActionPerformed

    private void SourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourceActionPerformed
        // TODO add your handling code here:
        String sourcetxt1=Source.getItemAt(Source.getSelectedIndex())+"";
        String destxt2=Destination.getItemAt(Destination.getSelectedIndex())+"";
      if(sourcetxt1.equals(destxt2) && !sourcetxt1.equals("-")&&!destxt2.equals("-"))
        {
            JOptionPane.showMessageDialog(null,"Source and Designation Cannot be same" );
           // return ;
            
        }
       else{
            if(sourcetxt1.equals("Karachi")&&destxt2.equals("Sukkur"))
       {
          Flightid.setText("Sk#") ;
          flightname.setText("AirBlue");
          Arrivaltime.setText("8am");
          departuretime.setText("10am");
          flightprice.setText("2000");
       }
      else if(sourcetxt1.equals("Sukkur")&&destxt2.equals("Karachi"))
       {
          Flightid.setText("Sk#") ;
          flightname.setText("AirBlue");
          Arrivaltime.setText("11am");
          departuretime.setText("1pm");
          flightprice.setText("2000");
          
       }
        else if(sourcetxt1.equals("Karachi")&&destxt2.equals("Islamabad"))
       {
          
           Flightid.setText("Sk#") ;
          flightname.setText("AirBlue");
          Arrivaltime.setText("2pm");
          departuretime.setText("3pm");
          flightprice.setText("2000");
          
          
       }
       
       else if(sourcetxt1.equals("Lahore")&&destxt2.equals("Karachi"))
       {
          Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("8am");
          departuretime.setText("11am");
          flightprice.setText("7000");
         
       }
        else if(sourcetxt1.equals("Karachi")&&destxt2.equals("Lahore"))
       {
            Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("12pm");
          departuretime.setText("3pm");
          flightprice.setText("3000");
       }
         else if(sourcetxt1.equals("Lahore")&&destxt2.equals("Islamabad"))
       {
        Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("3pm");
          departuretime.setText("4pm");
          flightprice.setText("3000");
       }
          else if(sourcetxt1.equals("Islamabad")&&destxt2.equals("Lahore"))
       {
          Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("4pm");
          departuretime.setText("5pm");
          flightprice.setText("3000");
       }
          else if(sourcetxt1.equals("Lahore")&&destxt2.equals("Sukkur"))
       {
             Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("7pm");
          departuretime.setText("9pm");
          flightprice.setText("2500");
       }
        else if(sourcetxt1.equals("Sukkur")&&destxt2.equals("Lahore"))
       {  Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("10pm");
          departuretime.setText("12am");
          flightprice.setText("2500");
       }
       
          else if(sourcetxt1.equals("Sukkur")&&destxt2.equals("Islamabad"))
       {
        Flightid.setText("Nk#") ;
          flightname.setText("SereneAir");
           Arrivaltime.setText("3pm");
          departuretime.setText("7pm");
          flightprice.setText("10000");
       }
            else if(sourcetxt1.equals("Islamabad")&&destxt2.equals("Sukkur"))
       {
          Flightid.setText("Nk#") ;
          flightname.setText("SereneAir");
           Arrivaltime.setText("9am");
          departuretime.setText("1pm");
          flightprice.setText("10000");
       }
             else if(sourcetxt1.equals("Islamabad")&&destxt2.equals("Karachi"))
       {
          Flightid.setText("ks#") ;
          flightname.setText("SereneAir");
           Arrivaltime.setText("9am");
          departuretime.setText("10am");
          flightprice.setText("2000");
       }
       else
            {
                
            }
      }
       
        
    }//GEN-LAST:event_SourceActionPerformed

    private void DestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationActionPerformed
        // TODO add your handling code here:
        String sourcetxt1=Source.getItemAt(Source.getSelectedIndex())+"";
        String destxt2=Destination.getItemAt(Destination.getSelectedIndex())+"";
       if(sourcetxt1.equals(destxt2) && !sourcetxt1.equals("-")&&!destxt2.equals("-"))
        {
            JOptionPane.showMessageDialog(null,"Source and Designation Cannot be same" );
           // return ;
            
        }
       else{
            if(sourcetxt1.equals("Karachi")&&destxt2.equals("Sukkur"))
       {
          Flightid.setText("Sk#") ;
          flightname.setText("AirBlue");
          Arrivaltime.setText("8am");
          departuretime.setText("10am");
          flightprice.setText("2000");
       }
      else if(sourcetxt1.equals("Sukkur")&&destxt2.equals("Karachi"))
       {
          Flightid.setText("Sk#") ;
          flightname.setText("AirBlue");
          Arrivaltime.setText("11am");
          departuretime.setText("1pm");
          flightprice.setText("2000");
          
       }
        else if(sourcetxt1.equals("Karachi")&&destxt2.equals("Islamabad"))
       {
          
           Flightid.setText("Sk#") ;
          flightname.setText("AirBlue");
          Arrivaltime.setText("2pm");
          departuretime.setText("3pm");
          flightprice.setText("2000");
          
          
       }
       
       else if(sourcetxt1.equals("Lahore")&&destxt2.equals("Karachi"))
       {
          Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("8am");
          departuretime.setText("11am");
          flightprice.setText("7000");
         
       }
        else if(sourcetxt1.equals("Karachi")&&destxt2.equals("Lahore"))
       {
            Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("12pm");
          departuretime.setText("3pm");
          flightprice.setText("3000");
       }
         else if(sourcetxt1.equals("Lahore")&&destxt2.equals("Islamabad"))
       {
        Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("3pm");
          departuretime.setText("4pm");
          flightprice.setText("3000");
       }
          else if(sourcetxt1.equals("Islamabad")&&destxt2.equals("Lahore"))
       {
          Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("4pm");
          departuretime.setText("5pm");
          flightprice.setText("3000");
       }
          else if(sourcetxt1.equals("Lahore")&&destxt2.equals("Sukkur"))
       {
             Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("7pm");
          departuretime.setText("9pm");
          flightprice.setText("2500");
       }
        else if(sourcetxt1.equals("Sukkur")&&destxt2.equals("Lahore"))
       {  Flightid.setText("pk#") ;
        flightname.setText("Pakistan International Airlines");
          Arrivaltime.setText("10pm");
          departuretime.setText("12am");
          flightprice.setText("2500");
       }
       
          else if(sourcetxt1.equals("Sukkur")&&destxt2.equals("Islamabad"))
       {
        Flightid.setText("Nk#") ;
          flightname.setText("SereneAir");
           Arrivaltime.setText("3pm");
          departuretime.setText("7pm");
          flightprice.setText("10000");
       }
            else if(sourcetxt1.equals("Islamabad")&&destxt2.equals("Sukkur"))
       {
          Flightid.setText("Nk#") ;
          flightname.setText("SereneAir");
           Arrivaltime.setText("9am");
          departuretime.setText("1pm");
          flightprice.setText("10000");
       }
             else if(sourcetxt1.equals("Islamabad")&&destxt2.equals("Karachi"))
       {
          Flightid.setText("ks#") ;
          flightname.setText("SereneAir");
           Arrivaltime.setText("9am");
          departuretime.setText("10am");
          flightprice.setText("2000");
       }
            
       else
            {
                
            }
        
       }     
    }//GEN-LAST:event_DestinationActionPerformed

    private void FlightidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightidActionPerformed
        // TODO add your handling code here:
       // Flightid
        
       
    }//GEN-LAST:event_FlightidActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
         String sourcetxt1=Source.getItemAt(Source.getSelectedIndex())+"";
        String destxt2=Destination.getItemAt(Destination.getSelectedIndex())+"";
        String flight_ID=Flightid.getText();
         String flight_name=flightname.getText();
         String flight_arrtime=Arrivaltime.getText();
         String flight_deptime=departuretime.getText();
          String flight_price=flightprice.getText();
          String Date1= Date.getText();
       // SimpleDateFormat dateformat =new SimpleDateFormat("yyyy-MM-dd");
       // String Date =dateformat.format(jDateChooser1.getDate());
      // String datestr= ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();//12
       ////SimpleDateFormat format = new SimpleDateFormat("MMM d, yyyy", Locale.ENGLISH);
       //Date date = format.parse(datestr);
     //  format.applyPattern("yyyy-MM-dd");
     //  String formattedDate = format.format(date);
      
                //PreparedStatement pstmt = connect.prepareStatement(query);
       
        
        if(sourcetxt1.equals("-") ||destxt2.equals("-")||Date1.equals(""))
            {
                JOptionPane.showMessageDialog(this, "Please fill out field");
               // return ;
            }
        else
        {
          
              try{
                 Class.forName("com.mysql.jdbc.Driver");
                String url="jdbc:mysql://localhost:3306/airline_ticket_booking_system";

                 connect=DriverManager.getConnection(url,"root","");
  String query="INSERT INTO flight_details (Flightid, Flightname, Source, Destination, Date, Arrival_time, Departure_time, Flight_price) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
                 pstmt = connect.prepareStatement(query);
                // pstmt = connect.createStatement();
                pstmt.setString(1,Flightid.getText());
                pstmt.setString(2,flightname.getText());
                pstmt.setString(3,Source.getItemAt(Source.getSelectedIndex())+"");
                pstmt.setString(4,Destination.getItemAt(Destination.getSelectedIndex())+"");
                pstmt.setString(5,Date.getText());//12
                pstmt.setString(6,Arrivaltime.getText());
                pstmt.setString(7,departuretime.getText());
                pstmt.setString(8,flightprice.getText());
                pstmt.executeUpdate();
                 JOptionPane.showMessageDialog(this, "ADDED SUCCESSFULLY");
                 // updatedb();
                 formWindowOpened(null);
                  Flightid.setText("");
                flightname.setText("");
                Arrivaltime.setText("");
                departuretime.setText("");
                flightprice.setText("");
                 Date.setText("");
               // jDateChooser1.setCalendar(null);
                Source.setSelectedIndex(0);
                Destination.setSelectedIndex(0);
              //   connect.close(); 
            
                

                
        }
              
                catch (ClassNotFoundException e) {
                    System.out.println("Class not found: " + e.getMessage());
                      e.printStackTrace();
                }
              catch(SQLException ex)
              {
                 System.out.print(ex.getMessage());
    
              }

        }        
               // Add.setEnabled(false);
                
                
                
        
        
       
    }//GEN-LAST:event_AddActionPerformed

    private void ArrivaltimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrivaltimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArrivaltimeActionPerformed

    private void departuretimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departuretimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departuretimeActionPerformed

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered
        // TODO add your handling code here:
        Add.setBackground(Color.BLACK);
        Add.setForeground(Color.white);
        Add.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        Add.setContentAreaFilled(true);
        Add.setBorderPainted(true);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
        // TODO add your handling code here:
         Add.setBackground(new Color(51,153,255));
        Add.setForeground(Color.black);
        Add.setBorderPainted(false);
        Add.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_AddMouseExited

    private void updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseEntered
        // TODO add your handling code here:
        update.setBackground(Color.BLACK);
        update.setForeground(Color.white);
        update.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        update.setContentAreaFilled(true);
        update.setBorderPainted(true);
    }//GEN-LAST:event_updateMouseEntered

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
        // TODO add your handling code here:
        update.setBackground(new Color(51,153,255));
        update.setForeground(Color.black);
        update.setBorderPainted(false);
        update.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_updateMouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
        delete.setBackground(Color.BLACK);
        delete.setForeground(Color.white);
        delete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        delete.setContentAreaFilled(true);
        delete.setBorderPainted(true);
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
        delete.setBackground(new Color(51,153,255));
        delete.setForeground(Color.black);
        delete.setBorderPainted(false);
        delete.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_deleteMouseExited

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
       
        
        String flight_ID=Flightid.getText();
         String flight_name=flightname.getText();
         String sourcetxt1=Source.getItemAt(Source.getSelectedIndex())+"";
        String destxt2=Destination.getItemAt(Destination.getSelectedIndex())+"";
        String date1=Date.getText();
         String flight_arrtime=Arrivaltime.getText();
         String flight_deptime=departuretime.getText();
          String flight_price=flightprice.getText();
          
       // SimpleDateFormat dateformat =new SimpleDateFormat("yyyy-MM-dd");
       // String Date =dateformat.format(jDateChooser1.getDate());
    //    String datestr= ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();//12
     //   SimpleDateFormat format = new SimpleDateFormat("MMM d, yyyy", Locale.ENGLISH);
      //  Date date = format.parse(datestr);
       // format.applyPattern("yyyy-MM-dd");
       // String formattedDate = format.format(date);
        int index=jTable1.getSelectedRow();
        
        if(sourcetxt1.equals(destxt2))
        {
            JOptionPane.showMessageDialog(null,"Source and Designation Cannot be same" );
            return;
        }
        if(sourcetxt1.isEmpty() ||destxt2.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Please fill out field");
                return ;
            }
        else
        {
           
                         int id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
    
        
         try{
             
                 Class.forName("com.mysql.jdbc.Driver");
                String url="jdbc:mysql://localhost:3306/airline_ticket_booking_system";
                connect=DriverManager.getConnection(url,"root","");
                Statement st=connect.createStatement();
                
   boolean b=st.execute("update  flight_details set Flightid ='"+flight_ID+"', Flightname='"+flight_name+"' ,Source='"+sourcetxt1+"',Destination='"+destxt2+"', Date='"+date1+"', Arrival_time='"+flight_arrtime+"', Departure_time='"+flight_deptime+"', Flight_price='"+flight_price+"' where ID = "+id);
             if(!b)
             {
                formWindowOpened(null);   
             }
         
                     
                Flightid.setText("");
                flightname.setText("");
                Arrivaltime.setText("");
                departuretime.setText("");
                flightprice.setText("");
                Date.setText("");
               // jDateChooser1.setCalendar(null);
                Source.setSelectedIndex(0);
                Destination.setSelectedIndex(0);
               // updatedb();
                
                
           //   connect.close();   
        }
                catch(Exception e)
                {
                   JOptionPane.showMessageDialog(this, e);
                }
        }
        
        
                
    }//GEN-LAST:event_updateActionPerformed

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(Color.BLACK);
        jButton1.setForeground(Color.white);
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jButton1.setContentAreaFilled(true);
        jButton1.setBorderPainted(true);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
          jButton1.setBackground(new Color(51,153,255));
        jButton1.setForeground(Color.black);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_jButton1MouseExited

    private void DestinationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DestinationMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_DestinationMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        HomePage1 hoe = new HomePage1();
        hoe.show();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
         dispose();
        searchform f2 = new searchform();
        f2.show();
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseExited

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        dispose();
        Delete f2 = new Delete();
        f2.show();
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jPanel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseEntered

    private void jPanel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel14MouseExited

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        // TODO add your handling code here:
        dispose();
        Updateform f1 = new Updateform();
        f1.show();
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jPanel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16MouseEntered

    private void jPanel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel16MouseExited

    private void jLabel43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel43MouseClicked
        // TODO add your handling code here
         dispose();
        FlightDetails f = new FlightDetails();
        f.show();
    }//GEN-LAST:event_jLabel43MouseClicked

    private void jPanel17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel17MouseEntered

    private void jPanel17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel17MouseExited

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
    

             
    }//GEN-LAST:event_AddMouseClicked

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            
          
                 Class.forName("com.mysql.jdbc.Driver");
                String url="jdbc:mysql://localhost:3306/airline_ticket_booking_system";
                 connect=DriverManager.getConnection(url,"root","");
                //Statement st=connect.createStatement();
                  DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
                 pstmt=connect.prepareStatement("Select * from flight_details ");
             
                 // int index=jTable1.getSelectedRow();
                rs= pstmt.executeQuery();
                  ResultSetMetaData data = rs.getMetaData();
                  q=data.getColumnCount();
                  tb1Model.setRowCount(0);
                  while(rs.next())
                  {
                      Vector columndata = new Vector();
                      for( i=1;i<=q;i++)
                      {
                          columndata.add(rs.getString("ID"));
                          columndata.add(rs.getString("Flightid"));
                           columndata.add(rs.getString("Flightname"));
                            columndata.add(rs.getString("Source"));
                             columndata.add(rs.getString("Destination"));
                              columndata.add(rs.getString("Date"));
                               columndata.add(rs.getString("Arrival_time"));
                                columndata.add(rs.getString("Departure_time"));
                                 columndata.add(rs.getString("Flight_price"));
                          
                      }
                      tb1Model.addRow(columndata);
                  }
             // connect.close();   
        }
                catch(Exception e)
                {
                   JOptionPane.showMessageDialog(null, e);
                }
    }//GEN-LAST:event_formWindowOpened

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        try{
            DefaultTableModel tb1Model=(DefaultTableModel)jTable1.getModel();
            int index=jTable1.getSelectedRow();

            Flightid.setText(tb1Model.getValueAt(index,1).toString());
            flightname.setText(tb1Model.getValueAt(index,2).toString());
            Object value = jTable1.getValueAt(index, 3);
            Object value2 = jTable1.getValueAt(index, 4);
            Source.setSelectedItem(value);
            Destination.setSelectedItem(value2);
            /*  Object cellValue = jTable1.getValueAt(index, 5);
            Date selectedDate = null;
            try {
                SimpleDateFormat format = new SimpleDateFormat("MMM d, yyyy", Locale.ENGLISH);
                selectedDate = format.parse((String) cellValue);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            //jDateChooser1.setDate(selectedDate);.*/
            Date.setText(tb1Model.getValueAt(index,5).toString());

            Arrivaltime.setText(tb1Model.getValueAt(index,6).toString());
            departuretime.setText(tb1Model.getValueAt(index,7).toString());
            flightprice.setText(tb1Model.getValueAt(index,8).toString());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        // TODO add your handling code here:
         LoginForm login = new LoginForm();
        if(JOptionPane.showConfirmDialog(login, "Confirm if you want to exit","",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           dispose();
           login.show();
                  
         // System.exit(0);
        }
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel39MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel39MouseClicked
        // TODO add your handling code here:
         LoginForm login = new LoginForm();
        if(JOptionPane.showConfirmDialog(login, "Confirm if you want to exit","",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
           dispose();
           login.show();
                  
         // System.exit(0);
        }
    }//GEN-LAST:event_jLabel39MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        FlightDetails ne1= new FlightDetails();
       
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new FlightDetails().setVisible(true);
                
                 
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Arrivaltime;
    private javax.swing.JTextField Date;
    private javax.swing.JComboBox<String> Destination;
    private javax.swing.JTextField Flightid;
    public javax.swing.JComboBox<String> Source;
    private javax.swing.JButton delete;
    private javax.swing.JTextField departuretime;
    private javax.swing.JTextField flightname;
    private javax.swing.JTextField flightprice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
